import { chmodSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import chalk from 'chalk';

function setupHooks() {
  const gitDir = '.git';
  if (!existsSync(gitDir)) {
    console.error(chalk.red('❌ Error: .git directory not found. Are you in the project root?'));
    return;
  }

  const hooksDir = join(gitDir, 'hooks');
  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true });
  }

  const hookContent = `#!/bin/bash
# Auto-generated by setup-hooks.ts
bun scripts/verify-dev.ts
`;

  for (const hookName of ['pre-commit', 'pre-push']) {
    const hookPath = join(hooksDir, hookName);
    writeFileSync(hookPath, hookContent);

    // Make executable
    chmodSync(hookPath, 0o755);
    console.log(chalk.green(`✅ Installed ${hookName} hook`));
  }
}

setupHooks();
